### ISSUE TITLE
Add support for horizontal mouse scroll

### ISSUE THREAD

**Issue by tylla** [freeplane/freeplane#141]
I'm getting used to my newly discovered Freeplane (it rocks BTW :)), but I'm unable to get the horizontal mouse scrolling to work (vertical works OK).
Am I doing something badly or is this feature really missing?

I'm using Freeplane on Debian 9.9 with Gnome 3.22.2 with oracle JRE 8u152.
The machine is a Lenovo Thinkpad X201 with Trackpoint  which works in any other program for both vertical and horizontal scrolling.

**Comment by dpolivaev** [comment]
AFAIK Java does not support horizontal mouse scrolling. You can use vertical scrolling holding shift button to get the result.

**Comment by tylla** [comment]
The "Shift+Scroll" trick is nice, thanks for the tip.
OTOH after a quick search it seems that this should already be solved in JAVA.
See here: https://stackoverflow.com/questions/2843314/how-to-use-my-trackpad-for-horizontal-mousewheel-scrolling-in-a-java-awt-scrollp

**Comment by Abnaxos** [comment]
IntelliJ IDEA supports it perfectly, also written in Swing.

**Comment by crose-project** [comment]
For me it seems there is still no direct mouse 'horizontal scrolling'. Shift-scroll is a workaround. 
A lot of other apps (Libre Office, DrawIO, probably all browser, ...) support it.
Are there technical issues or just not often enough requested?

**Comment by crose-project** [comment]
@dpolivaev Whoever like to implement it, let me know a post address and I will send a https://www.logitech.com/en-us/shop/p/mx-master-3s.910-006557 for testing and motivation.

**Comment by dpolivaev** [comment]
It turned out to be a bug in Freeplane, I fixed it now.

**Comment by dreirund** [comment]
> *It turned out to be a bug in Freeplane, I fixed it now.*

In Freeplane 1.13.2, on GNU/Linux, I still cannot use the horizontal scroll wheel, only `<Shift>`+vertical scroll.

**Comment by crose-project** [comment]
Same for me (still). Freeplane 1.13.2 / Ubuntu Mint Linux
