### ISSUE TITLE
Images are not proportionately zoomed when zooming the map

### ISSUE THREAD

**Issue by pmking369** [freeplane/freeplane#2300]
**Describe the bug**
In version 1.12.9, zooming the map is not effecting the zoom level of images.

**To Reproduce**
1. In any saved map insert an image and not necessary to change any zoom of the image
2. Either with ctrl + mouse wheel scroll or from view menu >>zoom try to change the zoom of the map
3. You will notice that only the zoom level of the node core text etc changes but the zoom percentage of image remains un changed.

**Expected behavior**
In the earlier versions the entire map will be zoomed in or zoomed out with all nodes and images zoomed proportionately.

**Desktop (please complete the following information):**
 - OS: [windows 11]
 - Java Version 8

**Comment by dpolivaev** [comment]
Already fixed in the latest preview 1.12.10_04

**Comment by pmking369** [comment]
Hi, I tried preview version you siggested, Looks like even in the preview 1.12.10_04 this issue still persists.

**Comment by dpolivaev** [comment]
Please upload

**Comment by dpolivaev** [comment]
Please upload some example map with an image and your image file all zipped so that I can check it
