### ISSUE TITLE
Regression in 1.9.14: Export map function applies highlighting to selected node in exported file

### ISSUE THREAD

**Issue by ilpssun** [freeplane/freeplane#272]
**Describe the bug**
When I choose to export a map to PDF, PNG etc., Freeplane exports the style for the currently selected node just as it is shown on the screen.  Before 1.9.14 this was correctly exported in the style that it would have, had it not been selected.  Since there is no apparent way for me to deselect all nodes, I cannot export a map without selection formatting at all.

**To Reproduce**
1. Open any saved mindmap; do not select any node
2. Choose File → Export map
3. Note the correct formatting in the output
4. Select any node
5. Choose File → Export map
6. Note highlighting being exported for selected node

**Expected behavior**
All nodes should be formatted according to their “base formatting” regardless of their selected state.

**Screenshots**
![map1](https://user-images.githubusercontent.com/835280/159716675-ece61860-fa0f-4db5-8bee-8157289ac682.png)
![map2](https://user-images.githubusercontent.com/835280/159716679-a808cd0c-388d-41ae-bf9c-bbaa3ba3cd9a.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.9.14

**Additional context**
This used to work in 1.9.12.

**Comment by ilpssun** [comment]
I just verified that the selection highlight is not present in the output file when exporting with version 1.9.12

**Comment by dpolivaev** [comment]
Fixed in previews 1.9.15_01 and 1.10.1_03
https://sourceforge.net/projects/freeplane/files/freeplane%20preview/

**Comment by ilpssun** [comment]
For me, this issue is still present in 1.9.15_01.  The selected node still shows up as highlighted in the exported file (tested PNG and PDF).

**Comment by dpolivaev** [comment]
Please attach your mind map file as well as your generated PDF and PNG

**Comment by ilpssun** [comment]
It seems that this is in fact depending on the map itself.  I had no issue in 1.9.14 when using one of the default templates.  However, with the attached map (created some time ago from a default template), this still happens.
[files.zip](https://github.com/freeplane/freeplane/files/8407714/files.zip)

**Comment by dpolivaev** [comment]
The fix is available in preview 1.10.1_05
